const mainCarousel = tns({
  container: '.main-carousel .slider-list',
  controls: true,
  prevButton: '.main-carousel .controls-arrow.is-prev',
  nextButton: '.main-carousel .controls-arrow.is-next',
  navContainer: '.main-carousel .nav-list',
  arrowKeys: true,
  autoplay: true,
  autoplayText: ['▶', '❚❚'],
  autoplayHoverPause: true,
  autoplayButton: '.main-carousel .autoplay-button',
  autoplayButtonOutput: true,
  mouseDrag: true,
  preventScrollOnTouch: true,
})
